In [1]:
## Install numpy library
## First prefernce, if ANACONDA is installed
## conda install numpy
## Second prefence
## pip install numpy
import numpy as np

In [3]:
pwd

'C:\\Users\\Thuto\\Desktop\\Digital Regenesys Dashboard\\Basic Data Science\\Codes'

In [5]:
myl = [1,2,30,40,-50]
print(type(myl))
# type(myl)
myl

<class 'list'>


[1, 2, 30, 40, -50]

In [7]:
# From list create array
mya = np.array(myl)
print(mya.dtype)
mya

int32


array([  1,   2,  30,  40, -50])

In [9]:
print(type(mya))
type(myl)

<class 'numpy.ndarray'>


list

In [11]:
sh = mya.shape
print(type(sh))
print(sh)
print(sh[0])

<class 'tuple'>
(5,)
5


In [13]:
mya.size

5

In [15]:
mya.itemsize

4

In [17]:
mya.dtype

dtype('int32')

In [19]:
myl

[1, 2, 30, 40, -50]

In [21]:
mylf = [1.0,2.0,3.0,4.0]
mylf

[1.0, 2.0, 3.0, 4.0]

In [23]:
myaf = np.array(mylf)

In [25]:
print(myaf.size)
myaf.itemsize

4


8

In [27]:
print(mya.size)
mya.itemsize

5


4

In [29]:
myaf.dtype


dtype('float64')

In [31]:
myaf.shape

(4,)

In [33]:
## Reshaping my 1-D
mylf = [1.0,2.0,3.0,4.0,10.0,-90,80,100,12,14,13,14]
myaf = np.array(mylf)
print(myaf.shape)
myaf

(12,)


array([  1.,   2.,   3.,   4.,  10., -90.,  80., 100.,  12.,  14.,  13.,
        14.])

In [35]:
X = myaf.reshape((2,2,3))
print(myaf.shape)
print(X.shape)
print(X)

(12,)
(2, 2, 3)
[[[  1.   2.   3.]
  [  4.  10. -90.]]

 [[ 80. 100.  12.]
  [ 14.  13.  14.]]]


In [37]:
X = myaf.reshape((6,2))
print(myaf.shape)
print(X.shape)
print(X)

(12,)
(6, 2)
[[  1.   2.]
 [  3.   4.]
 [ 10. -90.]
 [ 80. 100.]
 [ 12.  14.]
 [ 13.  14.]]


In [39]:
mylist = [9, 10, -20, 56, -4, 500, -20, 7, 8, 9]
mylist

[9, 10, -20, 56, -4, 500, -20, 7, 8, 9]

In [41]:
mya = np.array(mylist)
mya.dtype

dtype('int32')

In [43]:
## np.mean(mya)
## OR
mya.mean()

55.5

In [45]:
mya.sum()

555

In [47]:
mya.min()

-20

In [49]:
mya.argmin()

2

In [51]:
mya.argmax()

5

In [53]:
mya.std()

149.5073576784768

## Indexing and Slicing

In [56]:
print(mya.shape)
mya

(10,)


array([  9,  10, -20,  56,  -4, 500, -20,   7,   8,   9])

In [58]:
## Indexing
mya[6]

-20

In [60]:
# Slicing
print(mya[1:5])
mya[6:10]

[ 10 -20  56  -4]


array([-20,   7,   8,   9])

In [62]:
mya[5:] # index 5 to end

array([500, -20,   7,   8,   9])

In [64]:
mya[:6] # upto index 6 means excluding 6

array([  9,  10, -20,  56,  -4, 500])

In [66]:
print(mya)
mya[:] # Whole array

[  9  10 -20  56  -4 500 -20   7   8   9]


array([  9,  10, -20,  56,  -4, 500, -20,   7,   8,   9])

In [68]:
mya[-1]

9

In [70]:
myone = mya[ :5] # index start 0 to 4 (excluding 4)

In [73]:
myone

array([  9,  10, -20,  56,  -4])

In [75]:
# Assigning values
mya[5] = 10
mya[7] = 20
mya[2:5] = 1
mya

array([  9,  10,   1,   1,   1,  10, -20,  20,   8,   9])

In [77]:
mya

array([  9,  10,   1,   1,   1,  10, -20,  20,   8,   9])

In [79]:
# Getting subarray
mya_sub = mya[6:10]
print(type(mya_sub))
mya_sub


<class 'numpy.ndarray'>


array([-20,  20,   8,   9])

In [81]:
mya[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [83]:
mya_sub[:] = -100
mya_sub

array([-100, -100, -100, -100])

In [85]:
mya

array([   9,   10,    1,    1,    1,   10, -100, -100, -100, -100])

In [87]:
# copy and slicing difference
mya_copy = np.copy(mya[4:10])
mya_copy

array([   1,   10, -100, -100, -100, -100])

In [89]:
mya_copy[:] = 200
mya_copy

array([200, 200, 200, 200, 200, 200])

In [91]:
mya

array([   9,   10,    1,    1,    1,   10, -100, -100, -100, -100])

# 2-D slicing and referencing


In [94]:
y = [x for x in range(28)]
y

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27]

In [96]:
mya = np.array(y)
mya

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [98]:
mym = mya.reshape((7,4))
mym

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [100]:
# Indexing
mym[6,0:2]

array([24, 25])

In [102]:
mym[5:7,2:4]

array([[22, 23],
       [26, 27]])

In [104]:
mym[2:,2:]

array([[10, 11],
       [14, 15],
       [18, 19],
       [22, 23],
       [26, 27]])

In [106]:
mym[2:5,2:]

array([[10, 11],
       [14, 15],
       [18, 19]])

##Boolean from Arrays / conditional statement

In [109]:
mya

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [111]:
type(mya)

numpy.ndarray

In [113]:
b  = mya>10
b

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [115]:
mya[b]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [117]:
## Directly
mya[mya>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [119]:
myeven = mya[mya%2!=1]
myeven

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26])

## Numpy Operators

In [122]:
new_mya = np.copy(mya)
new_mya

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [124]:
# Element-wise addition
mya + new_mya

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54])

In [126]:
mya - new_mya

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [128]:
mya * new_mya

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625,
       676, 729])

In [130]:
mya+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [132]:
mya / new_mya

C:\Users\Thuto\AppData\Local\Temp\ipykernel_14904\3232117522.py:1: RuntimeWarning: invalid value encountered in divide
  mya / new_mya


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.])

In [134]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [136]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [138]:
# Creating a Identity matrix
np.eye(3,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.]])

In [140]:
np.eye(4,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [142]:
print(3 ** 4)
mya ** new_mya

81


array([          1,           1,           4,          27,         256,
              3125,       46656,      823543,    16777216,   387420489,
        1410065408,  1843829075,  -251658240, -1692154371, -1282129920,
        1500973039,           0,  1681328401,   457441280,  -306639989,
                 0,   878082373,   977272832, -1276351769,           0,
        1296002393,   603979776,  -714244925])

In [144]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [146]:
# creating numpy array
mya = np.arange(5,10)
mya

array([5, 6, 7, 8, 9])

In [148]:
# creating numpy array
# mya = np.arange(5,10)
mya = np.arange (5,-10,-2)
mya

array([ 5,  3,  1, -1, -3, -5, -7, -9])

In [150]:
mya = np.arange(0,-11,-2)
mya

array([  0,  -2,  -4,  -6,  -8, -10])

In [152]:
mya = np.arange(100,1000,100)
mya

array([100, 200, 300, 400, 500, 600, 700, 800, 900])

In [155]:
# Generating the numbers
np.linspace (0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [157]:
np.linspace(100,200, 21)

array([100., 105., 110., 115., 120., 125., 130., 135., 140., 145., 150.,
       155., 160., 165., 170., 175., 180., 185., 190., 195., 200.])

In [159]:
a = np.array([1,2,3]) 
print(a)

[1 2 3]
